@startuml
hide empty methods
hide empty attributes
hide circle
skinparam classAttributeIconSize 0
class ms_concept_Amateur_Video as "ms-concept:Amateur_Video"
ms_concept_Amateur_Video : a oa:SemanticTag, skos:Concept
ms_concept_Amateur_Video : skos:inScheme ms-concept:
ms_concept_Amateur_Video : skos:prefLabel "Amateur Video"
class ms_concept_Armed_Person as "ms-concept:Armed_Person"
ms_concept_Armed_Person : a oa:SemanticTag, skos:Concept
ms_concept_Armed_Person : skos:inScheme ms-concept:
ms_concept_Armed_Person : skos:prefLabel "Armed Person"
class ms_annot_1234153426_Amateur_Video as "ms-annot:1234153426-Amateur_Video"
ms_annot_1234153426_Amateur_Video : a oa:SemanticTag, fise:TopicAnnotation
class _http___images_zeit_de_____540x304_jpg_ as "<http://images.zeit.de/...-540x304.jpg>"
ms_annot_1234153426_Amateur_Video --> _http___images_zeit_de_____540x304_jpg_ : fise:extracted-from
ms_annot_1234153426_Amateur_Video --> ms_concept_Amateur_Video : fise:entity-reference\nskos:related
ms_annot_1234153426_Amateur_Video : fise:confidence 0.884379
_http___images_zeit_de_____540x304_jpg_ : a dctype:Image
_http___images_zeit_de_____540x304_jpg_ : dc:format "image/jpeg"
class _http___data_multisensorproject_eu_agent_imageAnnotator_ as "<http://data.multisensorproject.eu/agent/imageAnnotator>"
_http___data_multisensorproject_eu_agent_imageAnnotator_ : a prov:SoftwareAgent
_http___data_multisensorproject_eu_agent_imageAnnotator_ : foaf:name "CERTH Image Annotator v1.0"
class ms_annot_1234153426_Armed_Person as "ms-annot:1234153426-Armed_Person"
ms_annot_1234153426_Armed_Person : a oa:SemanticTag, fise:TopicAnnotation
ms_annot_1234153426_Armed_Person --> _http___images_zeit_de_____540x304_jpg_ : fise:extracted-from
ms_annot_1234153426_Armed_Person --> ms_concept_Armed_Person : skos:related\nfise:entity-reference
ms_annot_1234153426_Armed_Person : fise:confidence 0.35975
class ms_annot_1234153426 as "ms-annot:1234153426"
ms_annot_1234153426 : a oa:Annotation
ms_annot_1234153426 --> ms_annot_1234153426_Amateur_Video : oa:hasBody
class ms_annot_1234153426_Concepts3_Or_More_People as "ms-annot:1234153426-Concepts3_Or_More_People"
ms_annot_1234153426 --> ms_annot_1234153426_Concepts3_Or_More_People : oa:hasBody
ms_annot_1234153426 --> ms_annot_1234153426_Armed_Person : oa:hasBody
ms_annot_1234153426 -right-> _http___data_multisensorproject_eu_agent_imageAnnotator_ : oa:annotatedBy
ms_annot_1234153426 -left-> _http___images_zeit_de_____540x304_jpg_ : oa:hasTarget
ms_annot_1234153426 : oa:annotatedAt "2015-10-01T12:34:56"^^xsd:dateTime
ms_annot_1234153426 : oa:motivatedBy oa:tagging
ms_annot_1234153426_Concepts3_Or_More_People : a oa:SemanticTag, fise:TopicAnnotation
class ms_concept_Concepts3_Or_More_People as "ms-concept:Concepts3_Or_More_People"
ms_annot_1234153426_Concepts3_Or_More_People --> ms_concept_Concepts3_Or_More_People : skos:related\nfise:entity-reference
ms_annot_1234153426_Concepts3_Or_More_People --> _http___images_zeit_de_____540x304_jpg_ : fise:extracted-from
ms_annot_1234153426_Concepts3_Or_More_People : fise:confidence 0.731893
ms_concept_Concepts3_Or_More_People : a skos:Concept
ms_concept_Concepts3_Or_More_People : skos:inScheme ms-concept:
ms_concept_Concepts3_Or_More_People : skos:prefLabel "Concepts: 3 or More People"
@enduml
