@startuml
hide empty methods
hide empty attributes
hide circle
skinparam classAttributeIconSize 0
class twitter_MSR_Future_status_605786079153627136 as "twitter:MSR_Future/status/605786079153627136"
twitter_MSR_Future_status_605786079153627136 : a sioc:Post
class ms_content_939468 as "ms-content:939468"
twitter_MSR_Future_status_605786079153627136 --> ms_content_939468 : sioc:about
twitter_MSR_Future_status_605786079153627136 : dct:date "2015-06-02T20:20:00"^^xsd:dateTime
twitter_MSR_Future_status_605786079153627136 : sioc:content "@UNFCCC @EnergiewendeGER\n   That's great, just a shame it does not\n   translate into lower CO2. #Energiewende"
twitter_MSR_Future_status_605786079153627136 : sioc:has_creator twitter:MSR_Future
@enduml
