@startuml
hide empty methods
hide empty attributes
hide circle
skinparam classAttributeIconSize 0
class twitter_user_243236419 as "twitter_user:243236419"
twitter_user_243236419 : a sioc:UserAccount
class ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 as "ms-soc:civilengineering.dishwasher.energy_crisis.energy_policy.renewable.foodmanufacturing.homeappliances_243236419"
twitter_user_243236419 --> ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 : sioc:has_function
class ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances as "ms-soc:civilengineering.dishwasher.energy_crisis.energy_policy.renewable.foodmanufacturing.homeappliances"
ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : a sioc:Forum
class twitter_ as "twitter:"
ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances --> twitter_ : sioc:has_host
ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : dct:subject twitter_tag:policy_energy,\n  twitter_tag:renewable,\n  twitter_tag:dishwasher,\n  twitter_tag:foodmanufacturing,\n  twitter_tag:civilengineering,\n  twitter_tag:energy_crisis,\n  twitter_tag:homeappliances
class twitter_user_17463923 as "twitter_user:17463923"
twitter_user_17463923 : a sioc:UserAccount
class ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 as "ms-soc:civilengineering.dishwasher.energy_crisis.energy_policy.renewable.foodmanufacturing.homeappliances_17463923"
twitter_user_17463923 --> ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 : sioc:has_function
ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 : a sioc:Role
ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 --> ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : sioc:has_scope
ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 : ms:has_overall_influence 0.143948
ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 : ms:has_pagerank 0.0206942
ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_17463923 : ms:has_reachability 386.05
ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 : a sioc:Role
ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 --> ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances : sioc:has_scope
ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 : ms:has_overall_influence 0.143038
ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 : ms:has_pagerank 0.020222
ms_soc_civilengineering_dishwasher_energy_crisis_energy_policy_renewable_foodmanufacturing_homeappliances_243236419 : ms:has_reachability 434.15
@enduml
